version: '3'
services:
  employee-man:
    image: ernestwambua/tusafiri-employee-management:latest
    ports:
      - 5005:5005

  fleet-man:
    image: ernestwambua/tusafir-fleet-management:latest
    ports:
      - 5004:5004

  booking:
    image: ernestwambua/tusafiri-booking-system:latest
    ports:
      - 5003:5003

  feedback:
    image: ernestwambua/tusafiri-feedback-system:latest
    ports:
      - 5002:5002

  admin-ui:
    image: ernestwambua/tusafiri-admin-ui:latest
    ports:
      - 3003:3000

  api-gateway:
    image: ernestwambua/tusafiri-api-gateway:latest
    ports:
      - 5000:5000

  webapp:
    image: ernestwambua/tusafiri-webapp:latest
    ports:
      - 3000:3000
