version: '3'
services:
  employee-man:
    build:
      context: ./employee-management
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./employee-management:/app
    ports:
      - 5005:5005

  fleet-man:
    build:
      context: ./fleet-management
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./fleet-management:/app
    ports:
      - 5004:5004

  booking:
    build:
      context: ./booking-system
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./booking-system:/app
    ports:
      - 5003:5003

  feedback:
    build:
      context: ./feedback-system
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./feedback-system:/app

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api-gateway:/app
    ports:
      - 5000:5000

  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./admin-ui:/app
    ports:
      - 3005:3005

  webapp:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile.dev
    volumes:
      # - /app/node_modules
      - ./webapp:/app
    ports:
      - 3000:3000