version: '3.1'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oldVlZKeoyVpJzHPyIhi
    volumes:
      - /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5006:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: oldVlZKeoyVpJzHPyIhi
      ME_CONFIG_MONGODB_URL: ${DB_URI}

  employee-man:
    image: ernestwambua/tusafiri-employee-management:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 5005:5005
    restart: always
    depends_on:
      - db

  fleet-man:
    image: ernestwambua/tusafiri-fleet-management:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 5004:5004
    restart: always
    depends_on:
      - db

  booking:
    image: ernestwambua/tusafiri-booking-system:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 5003:5003
    restart: always
    depends_on:
      - db

  feedback:
    image: ernestwambua/tusafiri-feedback-system:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 5002:5002
    restart: always
    depends_on:
      - db

  api-gateway:
    image: ernestwambua/tusafiri-api-gateway:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db

  admin-ui:
    image: ernestwambua/tusafiri-admin-ui:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 3005:3005
    restart: always
    depends_on:
      - api-gateway

  webapp:
    image: ernestwambua/tusafiri-webapp:latest
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api-gateway
