@baseUrl = http://localhost:5004
@locationsApi = {{baseUrl}}/api/locations
@routesApi = {{baseUrl}}/api/routes
@busesApi = {{baseUrl}}/api/buses
@journeysApi = {{baseUrl}}/api/journeys

### Root route
GET {{baseUrl}}/

### CREATE Location
POST {{locationsApi}}/new
Content-Type: application/json

{
    "name": "Marsabit",
    "code": "MRS",
    "lat": 2.2247590,
    "lng": 9.3330776
}

### FETCH Locations
GET {{locationsApi}}/

### FETCH Location
GET {{locationsApi}}/623d8ff511e1cee33fc3ff36

### EDIT Location
PATCH {{locationsApi}}/edit?id=623d8ff511e1cee33fc3ff36
Content-Type: application/json

{
    "lat": 15.000001,
    "lng": 70.000002
}

### DELETE Location
DELETE {{locationsApi}}/delete?id=623c674c9ba3d91bd0a4ed67

### CREATE route
POST {{routesApi}}/new
Content-Type: application/json

{
    "name": "B8",
    "from": "WJR",
    "to": "MRS"
}

### FETCH routes
GET {{routesApi}}/

### FETCH route
GET {{routesApi}}/623d90d943fca7e8de609ceb

### EDIT route
PATCH {{routesApi}}/edit?id=623d90d943fca7e8de609ceb
Content-Type: application/json

{
    "from": "MRS",
    "to": "NRB"
}

### Delete route
DELETE {{routesApi}}/delete?id=623d90d943fca7e8de609ceb


### CREATE Bus
POST {{busesApi}}/new
Content-Type: application/json

{
    "regNo": "KDA 123A",
    "make": "Hound",
    "yom": 2021,
    "capacity": 5
}

### FETCH all buses
GET {{busesApi}}/

### FETCH bus
GET {{busesApi}}/623f40ddecaefea9476a6853

### EDIT bus
PATCH {{busesApi}}/edit?id=623d916643fca7e8de609d05
Content-Type: application/json

{
    "yom": 2017,
    "capacity": 10
}

### DELETE bus
DELETE {{busesApi}}/delete?id=623d916643fca7e8de609d05

### CREATE journey let date = new Date("2022-03-30T17:30+03:00").getTime()
POST {{journeysApi}}/new
Content-Type: application/json

{
    "bus": "KDA 123A",
    "route": "B1",
    "fare": 650,
    "departureTime": 1648650600000
}

### FETCH journeys
GET {{journeysApi}}/

### FETCH journey
GET {{journeysApi}}/623d9677f0e6c4aabf18a124

### EDIT journey
PATCH {{journeysApi}}/edit?id=623d9677f0e6c4aabf18a124
Content-Type: application/json

{
    "bookedSeats": []
}

### ADD drivers
PATCH {{journeysApi}}/add-drivers?id=623d9677f0e6c4aabf18a124
Content-Type: application/json

{
    "drivers": ["DRV0003/2015", "DRV0007/2017"]
}

### DELETE journey
DELETE {{journeysApi}}/delete?id=623d9677f0e6c4aabf18a124

### FETCH available journeys
GET {{journeysApi}}/available?route=B1