### Root route
GET http://localhost:5100/

### CREATE Location
POST http://localhost:5100/api/locations/new
Content-Type: application/json

{
    "name": "Bungoma",
    "code": "BNG",
    "lat": 2.2247590,
    "lng": 9.3330776
}

### FETCH Locations
GET http://localhost:5100/api/locations/

### FETCH Location
GET http://localhost:5100/api/locations/6239730ff87dc6d1af4fc24d

### EDIT Location
PATCH http://localhost:5100/api/locations/edit/6239730ff87dc6d1af4fc24d
Content-Type: application/json

{
    "lat": 15.000001,
    "lng": 70.000002
}

### DELETE Location
DELETE http://localhost:5100/api/locations/delete/6239730ff87dc6d1af4fc24d

### CREATE route
POST http://localhost:5100/api/routes/new
Content-Type: application/json

{
    "name": "A7",
    "pointA": "ELD",
    "pointB": "MSA"
}

### FETCH routes
GET http://localhost:5100/api/routes/

### FETCH route
GET http://localhost:5100/api/routes/623973c170002adbd553f5be

### EDIT route
PATCH http://localhost:5100/api/routes/edit/623973c170002adbd553f5be
Content-Type: application/json

{
    "pointA": "MSA",
    "pointB": "ELD"
}

### Delete route
DELETE http://localhost:5100/api/routes/delete/623973c170002adbd553f5be


### CREATE Bus
POST http://localhost:5100/api/buses/new
Content-Type: application/json

{
    "regNo": "KCA 111A",
    "make": "Scania",
    "yom": 2016,
    "capacity": 50,
}

### FETCH all buses
GET http://localhost:5100/api/buses/

### FETCH bus
GET http://localhost:5100/api/buses/6239745a70002adbd553f5d1

### EDIT bus
PATCH http://localhost:5100/api/buses/edit/6239745a70002adbd553f5d1
Content-Type: application/json

{
    "yom": 2017
}

### ADD_ROUTE
PATCH http://localhost:5100/api/buses/add-route?bus_id=6239745a70002adbd553f5d1
Content-Type: application/json

{
    "route_name": "A3"
}

### REMOVE_ROUTE
PATCH http://localhost:5100/api/buses/remove-route?bus_id=6239745a70002adbd553f5d1
Content-Type: application/json

{
    "route_name": "A3"
}

### DELETE bus
DELETE http://localhost:5100/api/buses/delete/623ae7da4298c29454921021