@baseUrl = http://localhost:5100
@locationsApi = {{baseUrl}}/api/locations
@routesApi = {{baseUrl}}/api/routes
@busesApi = {{baseUrl}}/api/buses
@journeysApi = {{baseUrl}}/api/journeys

### Root route
GET {{baseUrl}}/

### CREATE Location
POST {{locationsApi}}/new
Content-Type: application/json

{
    "name": "Bungoma",
    "code": "BNG",
    "lat": 2.2247590,
    "lng": 9.3330776
}

### FETCH Locations
GET {{locationsApi}}/

### FETCH Location
GET {{locationsApi}}/623c66d79ba3d91bd0a4ed5c

### EDIT Location
PATCH {{locationsApi}}/edit/623c66d79ba3d91bd0a4ed5c
Content-Type: application/json

{
    "lat": 15.000001,
    "lng": 70.000002
}

### DELETE Location
DELETE {{locationsApi}}/delete/623c66d79ba3d91bd0a4ed5c

### CREATE route
POST {{routesApi}}/new
Content-Type: application/json

{
    "name": "B7",
    "from": "KSM",
    "to": "NRB"
}

### FETCH routes
GET {{routesApi}}/

### FETCH route
GET {{routesApi}}/623c68493e7f8b05de2e579a

### EDIT route
PATCH {{routesApi}}/edit/623c68493e7f8b05de2e579a
Content-Type: application/json

{
    "from": "MSA",
    "to": "ELD"
}

### Delete route
DELETE {{routesApi}}/delete/623c68493e7f8b05de2e579a


### CREATE Bus
POST {{busesApi}}/new
Content-Type: application/json

{
    "regNo": "KCB 123C",
    "make": "Ford",
    "yom": 2018,
    "capacity": 15
}

### FETCH all buses
GET {{busesApi}}/

### FETCH bus
GET {{busesApi}}/623c5b283c4ae6beac7dcf56

### EDIT bus
PATCH {{busesApi}}/edit/623c5b283c4ae6beac7dcf56
Content-Type: application/json

{
    "yom": 2017
}

### DELETE bus
DELETE {{busesApi}}/delete/623c5b283c4ae6beac7dcf56

### CREATE journey let date = new Date("2022-03-30T17:30+03:00").getTime()
POST {{journeysApi}}/new
Content-Type: application/json

{
    "bus": "KCB 123C",
    "route": "B2",
    "fare": 650,
    "departureTime": 1648650600000
}

### FETCH journeys
GET {{journeysApi}}/

### FETCH journey
GET {{journeysApi}}/623c7d1ce2b563a09608cd97

### EDIT journey
PATCH {{journeysApi}}/edit/623c7d1ce2b563a09608cd97
Content-Type: application/json

{
    "bookedSeats": []
}

### ADD drivers
PATCH {{journeysApi}}/add-drivers?journey_id=623c6fa8f30f432a9b58a677
Content-Type: application/json

{
    "drivers": ["DRV0003/2015", "DRV0007/2017"]
}

### DELETE journey
DELETE {{journeysApi}}/delete/623c6fa8f30f432a9b58a677

### FETCH available journeys
GET {{journeysApi}}/available/all?route_name=B2