@baseUrl = http://localhost:5000
@bookingsApi = {{baseUrl}}/api/bookings


### ROOT route
GET {{baseUrl}}

### CREATE booking
POST {{bookingsApi}}/new
Content-Type: application/json

{
    "journey": "623c7d1ce2b563a09608cd97",
    "seats": ["623c7d0de2b563a09608cd73", "623c7d0de2b563a09608cd75"]
}

### FETCH bookings
GET {{bookingsApi}}/

### FETCH booking
GET {{bookingsApi}}/623cc012eb430d1359ee11d3

### EDIT booking
PATCH {{bookingsApi}}/edit/623c47776d05c90ddbb9405b
Content-Type: application/json

{
    "seats": ["623b27f4f43a2efdd58fc349", "623b27f4f43a2efdd58fc348", "623b27f4f43a2efdd58fc345", "623b27f4f43a2efdd58fc341"]
}

### DELETE booking
DELETE {{bookingsApi}}/delete/623cc183ab3f4a5df4ffc474