### Root route
GET http://localhost:5300/

### CREATE passenger
POST http://localhost:5300/api/passengers/new
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "username": "ernestwambua",
    "idNo": 37281546,
    "email": "ernestwambua2@gmail.com",
    "phoneNumber": "+254719286396",
    "password": "password"
}

### FETCH passengers
GET http://localhost:5300/api/passengers/

### FETCH passenger
GET http://localhost:5300/api/passengers/623ac336ea82c3bc8a8948e5

### EDIT passenger
PATCH http://localhost:5300/api/passengers/edit/623ac336ea82c3bc8a8948e5
Content-Type: application/json

{
    "email": "wambua@gmail.com"
}

### Change password
PATCH http://localhost:5300/api/passengers/change-password?passenger_id=623ac336ea82c3bc8a8948e5
Content-Type: application/json

{
    "oldPassword": "password",
    "newPassword": "password2"
}

### DELETE passenger
DELETE http://localhost:5300/api/passengers/delete/623ac336ea82c3bc8a8948e5