@base_url=http://localhost:5002
@feedbacks_url={{base_url}}/api/feedbacks

### Root route
GET {{base_url}}/

### Fetch feedbacks
GET {{feedbacks_url}}/

### CREATE feedback
POST {{feedbacks_url}}/new
Content-Type: application/json

{
    "type": "complement",
    "title": "Lorem Ipsum 9",
    "email": "ernestwambua2@gmail.com",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ex enim, euismod id faucibus quis."
}

###
@feedback_id = 624beafd0a6bdf5402b965c8

### FETCH feedback
GET {{feedbacks_url}}/{{feedback_id}}

### DELETE feedback
DELETE {{feedbacks_url}}/{{feedback_id}}

### FETCH spectfic types
GET {{feedbacks_url}}?type=complement