### Root route
GET http://localhost:5200/

### CREATE employee
POST http://localhost:5200/api/employees/new
Content-Type: application/json

{
    "firstName": "Benjamin",
    "lastName": "Mumasi",
    "idNo": 37281555,
    "email": "mumasibenjamin@gmail.com",
    "phoneNumber": "+254719286396",
    "employeeId": "DRV0007/2017",
    "password": "password",
    "role": "driver"
}

### FETCH employees
GET http://localhost:5200/api/employees/

### FETCH employee
GET http://localhost:5200/api/employees/6239b0a5bf038478788e10f4

### EDIT employee
PATCH http://localhost:5200/api/employees/edit/6239b0a5bf038478788e10f4
Content-Type: application/json

{
    "email": "wambua@gmail.com"
}

### Change password
PATCH http://localhost:5200/api/employees/change-password?employee_id=6239b0a5bf038478788e10f4
Content-Type: application/json

{
    "oldPassword": "password",
    "newPassword": "password2"
}

### Change role
PATCH http://localhost:5200/api/employees/change-role?employee_id=6239b0a5bf038478788e10f4
Content-Type: application/json

{
    "roleName": "admin"
}

### DELETE Employee
DELETE http://localhost:5200/api/employees/delete/6239b0a5bf038478788e10f4


### FETCH drivers
GET http://localhost:5200/api/employees/dept/drivers

### FETCH fleet managers
GET http://localhost:5200/api/employees/dept/fleet-managers

### FETCH snm managers
GET http://localhost:5200/api/employees/dept/snm-managers

### FETCH help desk
GET http://localhost:5200/api/employees/dept/help-desk