name: Docker Push
on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  Push-Containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Employees Management
        uses: docker/build-push-action@v2
        with:
          context: ./employee-management
          push: true
          tags: ernestwambua/tusafiri-employee-management:latest

      - name: Build and Push Fleet Management
        uses: docker/build-push-action@v2
        with:
          context: ./fleet-management
          push: true
          tags: ernestwambua/tusafiri-fleet-management:latest

      - name: Build and Push Booking System
        uses: docker/build-push-action@v2
        with:
          context: ./booking-system
          push: true
          tags: ernestwambua/tusafiri-booking-system:latest

      - name: Build and Push Feedback System
        uses: docker/build-push-action@v2
        with:
          context: ./feedback-system
          push: true
          tags: ernestwambua/tusafiri-feedback-system:latest

      - name: Build and Push API Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          push: true
          tags: ernestwambua/tusafiri-api-gateway:latest

      - name: Build and Push Admin UI
        uses: docker/build-push-action@v2
        with:
          context: ./admin-ui
          push: true
          tags: ernestwambua/tusafiri-admin-ui:latest

      - name: Build and Push Web App
        uses: docker/build-push-action@v2
        with:
          context: ./webapp
          push: true
          tags: ernestwambua/tusafiri-webapp:latest
